# Exercise 1: 4x4 submatrix sum

Implement a process_books function that:

Implement the validate_submatrix_sum function. Given a 4x4 two-dimensional list (matrix) and a target sum, check if the sum of elements in each 2x2 sub-matrix equals the target sum. The function returns True if all sub-matrices meet the target sum, otherwise False.

Remark: The submatrix includes all parts of the matrix, including the central 2x2 submatrix.
Expected Output

For matrix1 and target_sum1 = 6, the expected output should be True, as each 2x2 sub-matrix sums up to 6.
For matrix2 and target_sum2 = 6, the expected output should be False, as not all 2x2 sub-matrices sum up to 6.

In [4]:
def validate_submatrix_sum(matrix, target_sum):
    n,m=len(matrix),len(matrix[0])
    for i in range(n-1):
        for j in range(m-1):
            tmp = matrix[i][j]+matrix[i][j+1]+matrix[i+1][j]+matrix[i+1][j+1]
            if tmp != target_sum: return False
    return True  # Your implementation

if __name__ == "__main__":
    matrix1 = [
        [1, 2, 1, 2],
        [2, 1, 2, 1],
        [1, 2, 1, 2],
        [2, 1, 2, 1]
    ]

    target_sum1 = 6

    matrix2 = [
        [1, 1, 2, 2],
        [1, 1, 2, 2],
        [2, 2, 1, 1],
        [2, 2, 1, 1]
    ]
    target_sum2 = 6

    print(validate_submatrix_sum(matrix1, target_sum1))  # Should output True
    print(validate_submatrix_sum(matrix2, target_sum2))  # Should output False

True
False


# Exercise 2: Grouping Student Submissions

Implement a group_by_students function that:

Accepts a dictionary containing the student name for each submitted file name.
Returns a dictionary containing a list of submitted file names for each student in any order.
For example, in the following program, the group_by_students() function will return:
Expected Output:

{‘John’: [‘hw1_Code_John.py’, ‘hw1_John.txt’], ‘Mary’: [‘hw1_Mary.txt’, ‘hw2_Mary.txt’]}

In [6]:
def group_by_students(files):
    new_files = {}
    for hwname,name in files.items():
        if name in new_files:
            new_files[name].append(hwname)
        else:
            new_files[name] = [hwname]

    return new_files

if __name__ == "__main__":    
    files = {
        'hw1_Mary.txt': 'Mary',
        'hw1_Code_John.py': 'John',
        'hw1_John.txt': 'John',
        'hw2_Mary.txt': 'Mary'
    }   
    print(group_by_students(files))

{'Mary': ['hw1_Mary.txt', 'hw2_Mary.txt'], 'John': ['hw1_Code_John.py', 'hw1_John.txt']}


# Exercise 3: Finding Unique Fruits

Implement the unique_fruit method. When passed two lists of fruits, it will return a list containing the fruits that appear in either or both lists. The returned list should have no duplicates. In this example, if your function is correctly implemented, you should get the following output:

[‘Pineapple’, ‘Grape’, ‘Apple’, ‘Banana’, ‘Orange’]

In [14]:
def unique_fruit(list1, list2):
    new_set = set()
    for fruit in list1:
        new_set.add(fruit)
    for fruit in list2:
        # print(new_list)
        new_set.add(fruit)
        # print(new_list)
    new_list = []
    for x in new_set:
        new_list.append(x)
    return new_list

if __name__ == "__main__":
    list1 = ["Apple", "Banana", "Orange"]
    list2 = ["Grape", "Apple", "Pineapple", "Orange"]
    print(unique_fruit(list1, list2))

['Grape', 'Pineapple', 'Apple', 'Banana', 'Orange']


# Exercise 4: Select Specific Elements from an Array

Implement the select_elements function. It should select and return elements from a 2D numpy array, specified by a list of tuple indices. For the provided array and indices, the expected output is:

Expected output: [2 5 7]

In [40]:
import numpy as np

def select_elements(arr, indices):
    # new_arr = []
    # for x,y in indices:
    #     # print(arr[x][y])
    #     new_arr.append(arr[x][y])
    r,c = zip(*indices)
    return arr[r,c]

if __name__ == "__main__":
    arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
    indices = [(0, 1), (1, 1), (2, 0)]
    print(select_elements(arr, indices))

(0, 1, 2) (1, 1, 0)
[2 5 7]


# Exercise 5: Euclidean Distance Between Points

Implement the euclidean_distance function that calculates the Euclidean distance between two points in 3D space. The points are represented as numpy arrays. The expected output for the provided points is shown below:

Expected output: 5.196152422706632

In [52]:
import numpy as np

def euclidean_distance(point1, point2):

    return np.sqrt(np.sum((point1 - point2)**2))

if __name__ == "__main__":
    point1 = np.array([1, 2, 3])
    point2 = np.array([4, 5, 6])
    print(euclidean_distance(point1, point2))

5.196152422706632


# Exercise 6: Standardize Array Columns

Implement the standardize_columns function that standardizes each column of a 2D numpy array. Standardization means converting the column values so that each column has a mean of 0 and a standard deviation of 1. The function should return the standardized array.

The expected output for the provided input array is shown below:
```
[[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]
 ```

In [57]:
import numpy as np

def standardize_columns(arr):
    mean = np.sum(arr,axis=0)/ len(arr)
    # print(mean)
    std = np.sqrt(np.sum((arr-mean)**2,axis=0)/len(arr))
    # print(std)
    return (arr - mean) / std

if __name__ == "__main__":
    arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
    print(standardize_columns(arr))

[[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]
